In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [85]:
x = np.linspace(-50,50,10)
y = 2*x**3
n = len(x)
m = x[2] - x[1]

# Simple functions to approximate the first and second derivatives

In [48]:
def FO1stDer(y1,y2, h):
    # to find the 1st order 1st derivative at x1
    return (y2-y1)/h 

def SO1stDer(y0,y2,h):
    # to find the 2nd order 1st derivative at x1
    return (y2-y0)/(2*h)

def ForthO1stDer(y_1,y0,y2,y3,h):
     # to find the 4th order 1st derivative at x1
    return (y_1 - y3 - 8*y0 + 8*y2)/(12*h)

def SO2ndDer(y0,y1,y2,h):
    return (y0 - 2*y1 + y2)/(h**2)

In [49]:
print(x)
print(y)
# I want derivative at x[3]
h = x[4] - x[3]
print(FO1stDer(y[3], y[4], h))
print(SO1stDer(y[2], y[4], h))
print(ForthO1stDer(y[1],y[2],y[4],y[5],h))
print(SO2ndDer(y[2], y[3], y[4], h))

# 1st der at x[3] should be 33.33333
# 2nd der at x[3] should be 2

[-50.         -38.88888889 -27.77777778 -16.66666667  -5.55555556
   5.55555556  16.66666667  27.77777778  38.88888889  50.        ]
[2500.         1512.34567901  771.60493827  277.77777778   30.86419753
   30.86419753  277.77777778  771.60493827 1512.34567901 2500.        ]
-22.22222222222223
-33.33333333333332
-33.33333333333333
1.9999999999999964


In [86]:
def FirstDer4thOrder(n):
    O = np.empty((n-4,n))
    for i in range (n-4):
        for j in range(n):
          row = []
          for o in range(i):
            row.append(0)
          row.append(1)
          row.append(-8)
          row.append(0)
          row.append(8)
          row.append(1)
          for p in range(n - len(row)):
            row.append(0)
        O[i] = row
    return O

O = FirstDer4thOrder(n)
der1_matrix = 1/(12*m) * (O @ np.transpose(y))

[[ 1. -8.  0.  8.  1.  0.  0.  0.  0.  0.]
 [ 0.  1. -8.  0.  8.  1.  0.  0.  0.  0.]
 [ 0.  0.  1. -8.  0.  8.  1.  0.  0.  0.]
 [ 0.  0.  0.  1. -8.  0.  8.  1.  0.  0.]
 [ 0.  0.  0.  0.  1. -8.  0.  8.  1.  0.]
 [ 0.  0.  0.  0.  0.  1. -8.  0.  8.  1.]]
[-50.         -38.88888889 -27.77777778 -16.66666667  -5.55555556
   5.55555556  16.66666667  27.77777778  38.88888889  50.        ]
[4624.48559671 1671.81069959  324.07407407  828.18930041 3431.06995885
 8379.62962963]


# Constructing the Laplacian matrix to approximate the second derivative

In [81]:
# Getting the derivative at the inner points only 

def LaplacianMatrix(n):
    D = np.empty((n-2,n))
    for i in range (n-2):
        for j in range(n):
          row = []
          for o in range(i):
            row.append(0)
          row.append(1)
          row.append(-2)
          row.append(1)
          for p in range(n - len(row)):
            row.append(0)
        D[i] = row
    return D

D = LaplacianMatrix(n)
der2_matrix = 1/(m**2)* (D @ np.transpose(y))
